apiVersion: v1
kind: Secret
metadata:
  name: {{ include "umami.fullname" . }}-secret
  labels:
    {{- include "umami.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ include "umami.databaseUrl" . | b64enc | quote }}
  {{- if .Values.umami.appSecret }}
  APP_SECRET: {{ .Values.umami.appSecret | b64enc | quote }}
  {{- else }}
  APP_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.umami.hashSalt }}
  HASH_SALT: {{ .Values.umami.hashSalt | b64enc | quote }}
  {{- else }}
  HASH_SALT: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}